###########################################################
#  MAC0219 - Computação Paralela e Distribuída - 2018/01  #
#  Eugenio Augusto Jimenes                                #
#  Nº USP 7118981                                         #
#  MiniDesafio1 - Branch prediction                       #
###########################################################

all: run
run: compile
	./teste 1
	./teste 2
compile: minidesafio1.c
	gcc minidesafio1.c -o teste
clean:
	rm teste
